name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main # Change this to your default branch if it's not "main"

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18 # Use the Node.js version you prefer
                  cache: "pnpm"

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install Dependencies
              run: pnpm install

            - name: Build Project
              run: pnpm build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: dist
