name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main # Adjust this if your branch is different

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18 # Adjust the Node.js version as needed

            - name: Install PNPM
              run: npm i -g pnpm

            - name: Install Dependencies
              run: pnpm install

            - name: Build Project
              run: pnpm build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: dist
